name: local_database_for_uss_server

services:
  database:
    image: artecoglobalcompany/usee_database:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    container_name: uss_server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongodb_data:
    name: database_for_uss_server

  mongodb_config:
    name: config_for_uss_server
