name: recording_${PROCESS_NAME}

services:
  recording:
    image: artecoglobalcompany/usee_media_recorder:${DOCKER_TAG:-latest}
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=mongodb://127.0.0.1:${DB_PORT}/recording_${PROCESS_NAME}
      - SRV_INST_NAME=recording_${PROCESS_NAME}
      - RECORDING_PATH_TO_SAVE=/recording_files
      - GATEWAY_REMOTE_IP=${GRI:-ws://gateway:8001}
    container_name: recording_${PROCESS_NAME}
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - hypernode_recording_volume:/recording_files

volumes:
  hypernode_recording_volume:
    name: recording_${PROCESS_NAME}_hypernode_recording_volume