name: auth_${PROCESS_NAME}

services:
  
  auth:
    image: artecoglobalcompany/usee_id_verifier:${DOCKER_TAG:-latest}
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=mongodb://127.0.0.1:${DB_PORT}/auth_${PROCESS_NAME}
      - SRV_INST_NAME=auth_${PROCESS_NAME}
    container_name: auth_${PROCESS_NAME}
    restart: unless-stopped
    network_mode: "host"