name: arteco-hypernode-server

services:
  rabbitmqHypernode:
    image: rabbitmq:3.8.17-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hypernode-net
    environment:
      RABBITMQ_DEFAULT_USER: hypernode
      RABBITMQ_DEFAULT_PASS: hypernode
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    container_name: rabbitmqHypernode

  mongodb:
    image: mongo:4.4
    # ports:
    #   - 27017:27017
    networks:
      - hypernode-net
    volumes:
      - mongodb_data:/data/db
    container_name: mongoHypernode

  gateway-service:
      build:
        context: ../hypernode-server
        dockerfile: ../hypernode-server/docker/gateway.Dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
        args:
          SERVICE_NAME: "gateway-service"  # Replace with the desired service name
      # ports:
      #   - "8000:8000"
      #   - "5001:5001"
      #   #debugging port
      #   - 9229:9229
      networks:
        - hypernode-net

      environment:
        - GATEWAY_API_PORT=5001
        - GATEWAY_WS_PORT=8000
        - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@rabbitmqHypernode:5672}
        - DATABASE_URI=mongodb://mongoHypernode:27017/gateway-db
      container_name: gateway

  storage-service:
    build:
      context: ../hypernode-server/
      dockerfile: ../hypernode-server/docker/storage.Dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
      args:
        SERVICE_NAME: "storage-service"  # Replace with the desired service name
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@rabbitmqHypernode:5672}
      - DATABASE_URI=mongodb://mongodb:27017/storage-db
    container_name: storage

  event-service:
    build:
      context: ../hypernode-server/
      dockerfile: ../hypernode-server/docker/event.Dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
      args:
        SERVICE_NAME: "event-service"  # Replace with the desired service name
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@rabbitmqHypernode:5672}
      - DATABASE_URI=mongodb://mongodb:27017/event-db
    container_name: event

  camera-service:
    build:
      context: ../hypernode-server/
      dockerfile: ../hypernode-server/docker/camera.Dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
      args:
        SERVICE_NAME: "camera-service"  # Replace with the desired service name  
    networks:
       - hypernode-net
    environment:
      - ENABLE_FFMPEG=true
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@rabbitmqHypernode:5672}
      - DATABASE_URI=mongodb://mongodb:27017/camera-db
      - FFMPEG_PATH=/usr/bin/ffmpeg
    container_name: camera
  # deploy:
  #   resources:
  #     limits:
  #       memory: 1G  # Limita a un massimo di 1 GB di RAM
  #       cpus: '1.5'  # Limita a un massimo di 1.5 CPU
  #     reservations:
  #       memory: 512M  # Riserva almeno 512 MB di RAM
  #       cpus: '0.5'  # Riserva almeno 0.5 CPU

  auth-service:
    build:
      context: ../hypernode-server/
      dockerfile: ../hypernode-server/docker/auth.Dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
      args:
        SERVICE_NAME: "auth-service"  # Replace with the desired service name
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@rabbitmqHypernode:5672}
      - DATABASE_URI=mongodb://mongodb:27017/auth-db
    container_name: auth

  nginx:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
    ports:
        - "${SERVER_PORT:-80}:80"
        - "${SSL_PORT:-443}:443"
    container_name: nginxHypernode
    networks:
       - hypernode-net

  admin-gui:
    build:
      context: ../hypernode_server_gui
      dockerfile: ../hypernode_server_gui/dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
    container_name: adminHypernode
    networks:
      - hypernode-net
    environment:
      - VITE_BASE_NAME=settings
volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  hypernode-net:
      driver: bridge


#USAGE
# SERVER_PORT=80 SSL_PORT=443 RMQ=amqp://hypernode:hypernode@rabbitmqHypernode:5672  docker compose up -d
