name: additional_database

services:
  
  database:
    image: artecoglobalcompany/usee_database:${DOCKER_TAG:-latest}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    container_name: ${DB_NAME}
    restart: unless-stopped
    
volumes:
  mongodb_data:
      name: additional_database  # Nome unico per il volume
