name: local_database_for_${DB_NAME:-uss_database}

services:
  database:
    image: artecoglobalcompany/usee_database:${DOCKER_TAG:-latest}
    ports:
      - "${DB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db # <- path giusto
      - mongodb_config:/data/configdb # <- opzionale ma pulito
    container_name: ${DB_NAME:-uss_database} #in caso di installazione completa DB_NAME viene hardcodato in uss_database dall'installer
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongodb_data:
    name: database_for_${DB_NAME:-uss_database}

  mongodb_config:
    name: config_for_${DB_NAME:-uss_database}
