name: camera_${PROCESS_NAME}

services:

  camera:
    image: artecoglobalcompany/usee_live_streamer:${DOCKER_TAG:-latest}
    environment:
      - RABBITMQ_URI=${RMQ}
      - GATEWAY_URI=${GRI}
      - DATABASE_URI=mongodb://${DB_USERNAME:-hypernode}:${DB_PASSWORD:-hypernode}@127.0.0.1:${DB_PORT}/camera_${PROCESS_NAME}?authSource=admin
      - SRV_INST_NAME=camera_${PROCESS_NAME}
      - MACHINE=${MACHINE}
    container_name: camera_${PROCESS_NAME}
    restart: unless-stopped    
    network_mode: "host"
    cap_add:
      - NET_RAW
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
