name: event_${PROCESS_NAME}

services:
  
  event:
    image: artecoglobalcompany/usee_event_manager:${DOCKER_TAG:-latest}
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=mongodb://127.0.0.1:${DB_PORT}/event_${PROCESS_NAME}
      - SRV_INST_NAME=event_${PROCESS_NAME}
    container_name: event_${PROCESS_NAME}
    restart: unless-stopped
    network_mode: "host"

