name: ${PROCESS_NAME}

services:
  
  database:
    image: ${MONGO_IMAGE:-mongo:4.4}
    # ports:
    #   - 27050:27017
    networks:
      - hypernode-net
    volumes:
      - mongodb_data:/data/db
    container_name: ${DB_NAME}
    restart: unless-stopped

  storage:
    image: artecoglobalcompany/usee_media_recorder:latest
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=${DATABASE_URI}
      - SRV_INST_NAME=${PROCESS_NAME}
    container_name: ${PROCESS_NAME}
    restart: unless-stopped
    
volumes:
  mongodb_data:
      name: ${PROCESS_NAME}

networks:
  hypernode-net:
      driver: bridge

