name: storage_${PROCESS_NAME}

services:
  
  storage:
    image: artecoglobalcompany/usee_media_storage:${DOCKER_TAG:-latest}
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=mongodb://127.0.0.1:${DB_PORT}/storage_${PROCESS_NAME}
      - SRV_INST_NAME=storage_${PROCESS_NAME}
    container_name: storage_${PROCESS_NAME}
    restart: unless-stopped
    network_mode: "host"
