name: uSee_Service_Suite

services:
  messageBroker:
    image: rabbitmq:3.8.17-management
    ports:
      - "5672:5672"
    networks:
      - hypernode-net
    environment:
      RABBITMQ_DEFAULT_USER: hypernode
      RABBITMQ_DEFAULT_PASS: hypernode
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    container_name: messageBroker
    restart: unless-stopped
    
  database:
    image: ${MONGO_IMAGE:-mongo:4.4}
    networks:
      - hypernode-net
    volumes:
      - mongodb_data:/data/db
    container_name: database
    restart: unless-stopped

  gateway:
      image: artecoglobalcompany/usee_suite_manager:latest
      networks:
        - hypernode-net
      environment:
        - GATEWAY_API_PORT=5001
        - GATEWAY_WS_PORT=8000
        - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@messageBroker:5672}
        - DATABASE_URI=mongodb://database:27017/gateway-db
      container_name: gateway
      restart: unless-stopped

  storage:
    image: artecoglobalcompany/usee_media_recorder:latest
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@messageBroker:5672}
      - DATABASE_URI=mongodb://database:27017/storage-db
    container_name: storage
    restart: unless-stopped

  event:
    image: artecoglobalcompany/usee_event_manager:latest
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@messageBroker:5672}
      - DATABASE_URI=mongodb://database:27017/event-db
    container_name: event
    restart: unless-stopped

  camera:
    image: artecoglobalcompany/usee_live_streamer:latest
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@messageBroker:5672}
      - GATEWAY_REMOTE_IP=${GRI:-gateway:8000}
      - DATABASE_URI=mongodb://database:27017/camera-db
    container_name: camera
    restart: unless-stopped

  auth:
    image: artecoglobalcompany/usee_id_verifier:latest
    networks:
       - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ:-amqp://hypernode:hypernode@messageBroker:5672}
      - DATABASE_URI=mongodb://database:27017/auth-db
    container_name: auth
    restart: unless-stopped

  webserver:
    image: artecoglobalcompany/usee_web_server:latest
    ports:
        - "${SERVER_PORT:-80}:80"
        - "${SSL_PORT:-443}:443"
    container_name: webserver
    networks:
       - hypernode-net
    restart: unless-stopped

  configurator:
    image: artecoglobalcompany/usee_configurator:latest
    container_name: configurator
    networks:
      - hypernode-net
    restart: unless-stopped
    
volumes:
  rabbitmq_data:
  mongodb_data:
   
networks:
  hypernode-net:
      driver: bridge