name: ${PROCESS_NAME}

services:
  
  database:
    image: mongo:4.4
    # ports:
    #   - 27050:27017
    networks:
      - hypernode-net
    volumes:
      - mongodb_data:/data/db
    container_name: ${DB_NAME}
    restart: unless-stopped

  camera:
    build:
      context: ../../../hypernode-server/ 
      dockerfile: ../hypernode-server/docker/camera.Dockerfile  # or specify the path to your Dockerfile if it's not in the same directory
    networks:
      - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=${DATABASE_URI}
      - GATEWAY_REMOTE_IP=${GRI}
      - GATEWAY_WS_PORT=8000
    container_name: ${PROCESS_NAME}
    restart: unless-stopped
    
volumes:
  mongodb_data:
      name: ${PROCESS_NAME}  # Nome unico per il volume

networks:
  hypernode-net:
      driver: bridge

