name: snapshot_${PROCESS_NAME}

services:
  snapshot:
    image: artecoglobalcompany/usee_snapshot_recorder:${DOCKER_TAG:-latest}
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=mongodb://127.0.0.1:${DB_PORT}/snapshot_${PROCESS_NAME}
      - SNAPSHOT_PATH=/snapshot_files
      - GATEWAY_URI=${GRI}
      - SRV_INST_NAME=snapshot_${PROCESS_NAME}
      - SNAPSHOT_DISK_SPACE=${SNAPSHOT_DISK_SPACE:-10000000}
      - MACHINE=${MACHINE}
    container_name: snapshot_${PROCESS_NAME}
    restart: unless-stopped
    network_mode: "host"
    volumes:
        - ${SNAPSHOT_PATH}:/snapshot_files
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"