name: snapshot_${PROCESS_NAME}

services:
  snapshot:
    image: artecoglobalcompany/usee_snapshot_recorder:${DOCKER_TAG:-latest}
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=mongodb://127.0.0.1:${DB_PORT}/snapshot_${PROCESS_NAME}
      - SNAPSHOT_PATH_TO_SAVE=/snapshot_files
      - GATEWAY_REMOTE_IP=${GRI:-ws://gateway:8001}
      - SRV_INST_NAME=snapshot_${PROCESS_NAME}
    container_name: snapshot_${PROCESS_NAME}
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - hypernode_snapshot_volume:/snapshot_files

volumes:
  hypernode_snapshot_volume:
    name: snapshot_${PROCESS_NAME}_hypernode_snapshot_volume
 