name: ${PROCESS_NAME}

services:
  database:
    image: artecoglobalcompany/usee_database:${DOCKER_TAG:-latest}
    # ports:
    #   - 27050:27017
    networks:
      - hypernode-net
    volumes:
      - mongodb_data:/data/db
    container_name: ${DB_NAME}
    restart: unless-stopped

  snapshot:
    image: artecoglobalcompany/usee_snapshot_recorder:${DOCKER_TAG:-latest}
    networks:
      - hypernode-net
    environment:
      - RABBITMQ_URI=${RMQ}
      - DATABASE_URI=${DATABASE_URI}
      - SNAPSHOT_PATH_TO_SAVE=/snapshot_files
      - GATEWAY_REMOTE_IP=${GRI:-ws://gateway:8001}
      - SRV_INST_NAME=${PROCESS_NAME}
    container_name: ${PROCESS_NAME}
    restart: unless-stopped
    volumes:
      - hypernode_snapshot_volume:/snapshot_files

volumes:
  hypernode_snapshot_volume:
    name: ${PROCESS_NAME}_hypernode_snapshot_volume
  mongodb_data:
    name: ${PROCESS_NAME}_mongodb_data


networks:
  hypernode-net:
    driver: bridge
