name: Push USee Database On Demand

on:
  workflow_dispatch:
    inputs:
      BRANCH_BACKEND_REF:
        description: 'Checkout branch Backend (server)'
        required: true
        default: 'release_candidate'
      PLATFORMS:
        description: 'Architettura target Docker (piattaforma di build)'
        required: true
        type: choice
        options:
          - linux/amd64
          - linux/arm64
          - linux/amd64,linux/arm64
          - linux/arm/v7
          - linux/arm/v6
        default: 'linux/amd64,linux/arm64'

jobs:
  build_and_push_database:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: ${{ github.event.inputs.PLATFORMS }}

    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          path: deploy

      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          repository: Arteco-Global/hypernode-server
          ref: ${{ github.event.inputs.BRANCH_BACKEND_REF }}
          path: hypernode-server
          token: ${{ secrets.GIT_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: DockerHub Login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" \
            | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: DockerHub check
        run: docker info

      - name: BuildDatabaseLatest
        run: |
          docker buildx build \
            --platform=${{ env.PLATFORMS }} \
            --build-arg MONGO_VERSION=latest \
            -f hypernode-server/docker/database/database.Dockerfile \
            -t artecoglobalcompany/usee_database:latest \
            --push hypernode-server

      - name: BuildDatabaseAvxSupport
        run: |
          docker buildx build \
            --platform=${{ env.PLATFORMS }} \
            --build-arg MONGO_VERSION=4.4.18 \
            -f hypernode-server/docker/database/database.Dockerfile \
            -t artecoglobalcompany/usee_database:avx_support \
            --push hypernode-server
